kind: Secret
apiVersion: v1
metadata: 
  name: linkerd-sweep-k8s-tls
type: kubernetes.io/tls
data:
  tls.crt: | 
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGekNDQWYrZ0F3SUJBZ0lRS1JTY2RhSEhX
    MGlSaGVoMXlCSUVFVEFOQmdrcWhraUc5dzBCQVFzRkFEQWsKTVNJd0lBWURWUVFERXhsc2FXNXJa
    WEprTFhOM1pXVndMbVJsWm1GMWJIUXVjM1pqTUI0WERUSXlNRE15TVRFNApNREEwTmxvWERUTXlN
    RE14T0RFNE1EQTBObG93SkRFaU1DQUdBMVVFQXhNWmJHbHVhMlZ5WkMxemQyVmxjQzVrClpXWmhk
    V3gwTG5OMll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5OVE9q
    Z3cKeWswaElVcWFkeEJYRFF0VTE4ZkdwZUJNQkhuTmxZcVFXQVhpbXo2ekN3SzF4aGRIcURDOHlG
    c1dNaUtPNEFvcgpmQURoNFZsQmxkRzhFZlEwZStQcnFnNTQ0TVJKVUtwRUJkQjhWRXUyRk11RFhZ
    bWN5d3p5OU1YR25EN1lSaWF6Cnd6YUNTVXBkZkZ4dmZzZk1RNTBMT3hQaXBzOExlaHVmM0dVRmJD
    bWpJWmtnUjFnRGV2ek9vZzRxaXViRWhobCsKUzZqeitmYkdFcjQ0dWV1RUxpSGY3OGZFM0RmR3M2
    eituekI2TFp4Tk5laUI3NUFYVm1IUThXbTB4TGZaMWxUOQpjRm1IUmJhQzZaVjN0ejVtejBMRWtQ
    TGFOZW9SUC8xY3RtNGZqM0JsOWdibmVCMndPVVpEY2srcU1yRmQwU3lxCk1nZjZabUo0SzhvVmtt
    RUNBd0VBQWFORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUkKTUFZQkFm
    OENBUUV3SFFZRFZSME9CQllFRkl3SHdXRVoxTnN1T2xrRFBZbXlFcFEyczdhTU1BMEdDU3FHU0li
    MwpEUUVCQ3dVQUE0SUJBUUFLMTM1OWt1RTVMZWNYa1ZkVG5HNWw1SnkzZGtUbWIwd0g1UzZJME5S
    M0tFS3JRS3c3CnNnTzAwMEtBMzNIVURMNGs1ZFljVENCbUFrUkV6NzFCeXFmbWNZS0JTSWYrVTdR
    WnMxZG1PYURqUS9ueUZvYUoKWDRwYkdGOXRwQkJFU1RUak9mYWRIcktZalNWMUpjeWZ0YXVqQjNt
    SThQSzI5aGZyWSsyK3ZMOENobE90U2ZVSgpGc1dZSEJQNEFLNjltYkNocE42WDlmNmJmamo2SlVj
    bE9Mc0w4TDdpcHV0ZlVIWEI1OS84RzJYSnVPWVgrNnVwCkVQQVNHcTNsZVFodk5pK3dZYmMzaVoy
    bUdTT0VNeDJjdndEWmovNlFqWUh0VkJ1Y3k0WnhMbks1VmlsNTlNRmEKYlhVZnY4cStLYi9QK3Bw
    NXJ0OXdxZ0V1bmtXZ0RNNkNvRjl4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMDFNNk9EREtU
    U0VoU3BwM0VGY05DMVRYeDhhbDRFd0VlYzJWaXBCWUJlS2JQck1MCkFyWEdGMGVvTUx6SVd4WXlJ
    bzdnQ2l0OEFPSGhXVUdWMGJ3UjlEUjc0K3VxRG5qZ3hFbFFxa1FGMEh4VVM3WVUKeTROZGlaekxE
    UEwweGNhY1B0aEdKclBETm9KSlNsMThYRzkreDh4RG5RczdFK0ttend0Nkc1L2NaUVZzS2FNaApt
    U0JIV0FONi9NNmlEaXFLNXNTR0dYNUxxUFA1OXNZU3ZqaTU2NFF1SWQvdng4VGNOOGF6clA2Zk1I
    b3RuRTAxCjZJSHZrQmRXWWREeGFiVEV0OW5XVlAxd1dZZEZ0b0xwbFhlM1BtYlBRc1NROHRvMTZo
    RS8vVnkyYmgrUGNHWDIKQnVkNEhiQTVSa055VDZveXNWM1JMS295Qi9wbVluZ3J5aFdTWVFJREFR
    QUJBb0lCQUN3a3hKS2NUb1lTRjV3Mwo3QXN6dy92TCswODJCY3gyMUxDRTYyb0lnUHFwdlhnNWVt
    RlVpMDZ0bjBxZkJOTlNMYUxlYVpwMlB1OElRRVNlCjJLYjVQRjdnMzhoYW9DbHB3cm45L3FXeWsr
    eGJMRmlzYm1lY3gxdEpyM2pDLzdLWXJHYk1Vc3NlM2ZaeS9OQlYKK3Zac0svV2NpN3N3YjJUV0Fi
    WmFWV1dUM1R3VXByYno1UTJrT1lHcmswTGd0bnR3NkNjZEd0eGU4RjV4cnhBTApDcGRKcXA3aFdO
    YWpBY2F1MkRhQy9QMmMyRC93cXprUmRZWXJlWTNseHNGczdKcEh6NUU2Mk1QeXJGbzl1M3FBCjVQ
    SXhBK0wwVVZJS0ZHamFQSXZMS1hNNENWWkJvOVljWG00cTZmTzZrWVlxekZUQWFITlZEQjAyUXk0
    VXRCNlMKVW5rUVNXa0NnWUVBNVpzRks5NVh0K3M5MXZWYmZuN0RKTjFkZXA4TFgvT1diR0pYRFV2
    ZUVHSTNtYXhMSE5LMwphNVJFYnhYYUk5YlMzSW5Yb3VYOHluVDA2SWU3MVJvZzk0SCt2a3liVXBh
    M3hxRWhoeXpmaEpLdFo0U2lJb25yClIzRXBWYndUYm1FMHlZWUxtYTdtak5oc01QYUxNa1JUU3ll
    dlAvbXhyQkZmOWF0VjYxNFB0NzhDZ1lFQTY1NDkKR0V1bE84MHErZVBZaW9TdWdMUEZlcTFRNlNP
    eGN4R1NGeGZYcHo2bWROSFB3ZzcxY3pzM1p6K2hiN1JLL2ltRgpwUjVBZkFqSXFHODg1emZsVEUv
    ZzBPdmJueThMRkVRVjRvNTdJeE5rV244Z29MSGpSaXgzZC80RG1IM08zdzEzCm9tdW1qemZkOGhV
    U09XVkZoMUJJY0hnNlRVSlc3aXJEMWV0a1BkOENnWUVBMCtESzArR1k5dHE1TlMwem9qWmQKNUIz
    Mnpsb0lDQ0pqbEY3blVCakxzampBY0NvREluVDgxK1I1aGowWEVPMkRwZ241bUpROVE2TE1BZXlI
    azY1Sgo3N3poRkVEak1FSnZFbmZNMWMyOThidmRFdUxkTDV3d0pyd3hWYkY2Q09qZzZucXRKOE96
    Y3hPZ08wcTN4c293ClJ2RTNFb1ZieEpwQUFCZDg4UGJhOEVjQ2dZRUF6emtwbEgrYlFDQXU1djVz
    Q1UrdVJnVlY3cElWOGlYeFFEbTQKMmRTZlZ6a3pudFNVdTZENllMRTVCZmFobmlQY1BQTDUxb0hu
    eHU3V3c4U3B0TldsTmx1ZVowQzR0S1RrUXB1cQovOG0rSk5nK1Q1VTFkZjlkMnU3cTE3NnhIT0d4
    R3QyMlZVUUdoamxsV3k4TEN5MjFXOC9SRmhHM2ZSR1djUHR0CnAydlNpdE1DZ1lFQXVja2MwL0J1
    enZLVy9xYzRFOVN6cTJ4OEs0clpQeVA0T0t5SWpacFhDSDFuVnFISTMvZUYKS1Z4SWV6aUVPVCs0
    L0xlL3R4a2hmS3dzSGF1UzVQSXE3NEY2dWtKSklKNmJnNVNPOTI2RFBsRWM0VUVXbXUrUgpRUDVz
    bXRNTy82dGZlODZFdkZubUZBUWJ3czYxc2NBbnh6U2hEN281WjNoNW13U3pxK2J4ZmVVPQotLS0t
    LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: linkerd-sweep-webhook
webhooks:
  - name: linkerd-sweep.default.svc
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    clientConfig:
      service:
        name: linkerd-sweep
        namespace: default
        path: "/mutate"
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGekNDQWYrZ0F3SUJBZ0lRS1JTY2RhSEhX
        MGlSaGVoMXlCSUVFVEFOQmdrcWhraUc5dzBCQVFzRkFEQWsKTVNJd0lBWURWUVFERXhsc2FXNXJa
        WEprTFhOM1pXVndMbVJsWm1GMWJIUXVjM1pqTUI0WERUSXlNRE15TVRFNApNREEwTmxvWERUTXlN
        RE14T0RFNE1EQTBObG93SkRFaU1DQUdBMVVFQXhNWmJHbHVhMlZ5WkMxemQyVmxjQzVrClpXWmhk
        V3gwTG5OMll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5OVE9q
        Z3cKeWswaElVcWFkeEJYRFF0VTE4ZkdwZUJNQkhuTmxZcVFXQVhpbXo2ekN3SzF4aGRIcURDOHlG
        c1dNaUtPNEFvcgpmQURoNFZsQmxkRzhFZlEwZStQcnFnNTQ0TVJKVUtwRUJkQjhWRXUyRk11RFhZ
        bWN5d3p5OU1YR25EN1lSaWF6Cnd6YUNTVXBkZkZ4dmZzZk1RNTBMT3hQaXBzOExlaHVmM0dVRmJD
        bWpJWmtnUjFnRGV2ek9vZzRxaXViRWhobCsKUzZqeitmYkdFcjQ0dWV1RUxpSGY3OGZFM0RmR3M2
        eituekI2TFp4Tk5laUI3NUFYVm1IUThXbTB4TGZaMWxUOQpjRm1IUmJhQzZaVjN0ejVtejBMRWtQ
        TGFOZW9SUC8xY3RtNGZqM0JsOWdibmVCMndPVVpEY2srcU1yRmQwU3lxCk1nZjZabUo0SzhvVmtt
        RUNBd0VBQWFORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUkKTUFZQkFm
        OENBUUV3SFFZRFZSME9CQllFRkl3SHdXRVoxTnN1T2xrRFBZbXlFcFEyczdhTU1BMEdDU3FHU0li
        MwpEUUVCQ3dVQUE0SUJBUUFLMTM1OWt1RTVMZWNYa1ZkVG5HNWw1SnkzZGtUbWIwd0g1UzZJME5S
        M0tFS3JRS3c3CnNnTzAwMEtBMzNIVURMNGs1ZFljVENCbUFrUkV6NzFCeXFmbWNZS0JTSWYrVTdR
        WnMxZG1PYURqUS9ueUZvYUoKWDRwYkdGOXRwQkJFU1RUak9mYWRIcktZalNWMUpjeWZ0YXVqQjNt
        SThQSzI5aGZyWSsyK3ZMOENobE90U2ZVSgpGc1dZSEJQNEFLNjltYkNocE42WDlmNmJmamo2SlVj
        bE9Mc0w4TDdpcHV0ZlVIWEI1OS84RzJYSnVPWVgrNnVwCkVQQVNHcTNsZVFodk5pK3dZYmMzaVoy
        bUdTT0VNeDJjdndEWmovNlFqWUh0VkJ1Y3k0WnhMbks1VmlsNTlNRmEKYlhVZnY4cStLYi9QK3Bw
        NXJ0OXdxZ0V1bmtXZ0RNNkNvRjl4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["jobs"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-sweep
  labels:
    linkerd.io/extension: failover
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-sweep
  labels:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-sweep
subjects:
- kind: ServiceAccount
  name: linkerd-sweep
  namespace: default
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-sweep
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-sweep
spec:
  type: ClusterIP
  selector:
    app: linkerd-sweep
  ports:
  - name: https
    port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-sweep
spec:
  selector:
    matchLabels:
      app: linkerd-sweep
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: linkerd-sweep
    spec:
      serviceAccountName: linkerd-sweep
      containers:
      - name: linkerd-sweep
        image: linkerd-sweep:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/run/sweep/tls
          name: sweep-tls
          readOnly: true
      volumes:
      - name: sweep-tls
        secret:
          secretName: linkerd-sweep-k8s-tls
